name: DragonEggTracker
version: '1.0-SNAPSHOT'
main: me.maxgim234.dragonEggTracker.DragonEggTracker
api-version: '1.21'

commands:
  dragon:
    description: Main Dragon Egg Tracker command
    usage: |
      /dragon help - Shows help
      /dragon owner - Shows who owns the Dragon Egg
      /dragon locate - Shows the Dragon Egg location (Admin)
      /dragon recipe - Displays the Tracker Compass recipe
      /dragon reload - Reloads the plugin (Admin)
    aliases: [dragoneggtracker] [det]

permissions:
  dragoneggtracker.admin:
    description: Allows access to admin commands
    default: op
  dragoneggtracker.craft:
    description: Allows crafting the Dragon Egg Tracker compass
    default: true

